---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--force --verbose'

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.13.10
  ansible_runner:
    package_pip: ansible-runner>=2.3.2
  python: requirements.txt
  galaxy: requirements.yml

additional_build_steps:
  append_final:
    - RUN curl -O https://mirror.openshift.com/pub/rhacs/assets/4.1.2/bin/linux/roxctl
    - RUN chmod +x roxctl
    - RUN mv roxctl /usr/local/bin/roxctl
