---
- name: Check for a matching directory in the fips-assessments repo
  ansible.builtin.stat:
    path: "{{ fips_repo }}/{{ package_name }}/tasks/main.yml"
  register: path_exists

- name: If path exists, execute main.yml
  ansible.builtin.include_tasks: "{{ fips_repo }}/{{ package_name }}/tasks/main.yml"
  register: fips_assessment_result
  when: path_exists.stat.exists
